image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info
  - 'which ssh-agent || ( apk update && apk add openssh-client)'
  - eval $(ssh-agent -s)
  - apk add curl
  - apk add py-pip
  - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

stages:
 - build
 - release
 - deploy

build:
 stage: build
 script:
 - docker-compose build
 - curl localhost:8000/api/v1/users/

#deploy-containers:
# stage: deploy
# script:
# - export DOCKER_HOST=tcp://192.x.x.x:2375
# - docker-compose down
# - docker-compose up -d
# tags:
# - docker-test
#
#
#prod-deploy-containers:
# stage: deploy
# script:
# - pwd && ls -l
# - ./docker-compose-vps-down.sh
# - ./docker-compose-vps-up.sh
# when: manual
# tags:
# - docker-prod