image: docker:stable
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
services:
  - docker:dind
before_script:
  - docker info
  - 'which ssh-agent || ( apk update && apk add openssh-client)'
  - eval $(ssh-agent -s)
  - apk add curl

stages:
 - build
 - release
 - deploy

build:
 stage: build
 script:
 - curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
 - chmod +x /usr/local/bin/docker-compose
 - docker-compose build
 - curl localhost:8000/api/v1/users/

#deploy-containers:
# stage: deploy
# script:
# - export DOCKER_HOST=tcp://192.x.x.x:2375
# - docker-compose down
# - docker-compose up -d
# tags:
# - docker-test
#
#
#prod-deploy-containers:
# stage: deploy
# script:
# - pwd && ls -l
# - ./docker-compose-vps-down.sh
# - ./docker-compose-vps-up.sh
# when: manual
# tags:
# - docker-prod