image: docker:stable
stages:
  - build_image
  - deploy
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
services:
  - docker:dind
before_script:
  - docker info
  - 'which ssh-agent || ( apk update && apk add openssh-client)'
  - eval $(ssh-agent -s)
  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - SSH_PRIVATE_KEY=$(echo  "$SSH_PRIVATE_KEY" | base64)
  - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - ssh-keyscan -t rsa "$ORGHUB_TEST_SERVER" >> ~/.ssh/known_hosts
#   - echo '$ORGHUB_TEST_SERVER" ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFh2TgeBiYT/DKSl5sJAhqOPYBgTr3bbxnhLFju9Z0jt22HPxVVuy+P7te/BGED9oWsf4SmC/5vVsXyjZVQaaF8=' >> ~/.ssh/known_hosts
# build_image:
#   stage: build_image
#   script:
#   - docker network create tickethub_net
#   - docker build -t $CI_REGISTRY/sejuba1/django-saas-backoffice/image:latest .
#   - docker push $CI_REGISTRY/sejuba1/django-saas-backoffice/image:latest
    
staging:
  type: deploy
  script:
  - ssh "$ORGHUB_TEST_USER"@"$ORGHUB_TEST_SERVER" 'cd /opt/django-saas-backoffice && sudo git pull && sudo docker-compose down -v --rmi all --remove-orphans'
  - ssh "$ORGHUB_TEST_USER"@"$ORGHUB_TEST_SERVER" 'cd /opt/django-saas-backoffice && docker network create tickethub_net && docker-compose up --build'

# production:
#   type: deploy
#   script:
#   - echo "$ORGHUB_TEST_SERVER"
#   - ssh "$ORGHUB_TEST_USER"@"$ORGHUB_TEST_SERVER" 'cd /opt/django-saas-backoffice && pwd'
#   only:
#   - 'master'
#   when: manual
  
# image: docker:stable
# variables:
#   DOCKER_HOST: tcp://docker:2375/
#   DOCKER_DRIVER: overlay2
# services:
#   - docker:dind
# before_script:
#   - docker info
#   - 'which ssh-agent || ( apk update && apk add openssh-client)'
#   - eval $(ssh-agent -s)
#   ##
#   ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
#   ## We're using tr to fix line endings which makes ed25519 keys work
#   ## without extra base64 encoding.
#   ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
#   ##
#   - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add - > /dev/null
#   - mkdir -p ~/.ssh
#   - chmod 700 ~/.ssh
#   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

# build_image:
#   stage: build_image
#   script:
#     - docker network create tickethub_net
#     # - docker-compose build -t registry.gitlab.com/sejuba1/django-saas-backoffice .
#     # - docker-compose push registry.gitlab.com/sejuba1/django-saas-backoffice
#     - docker build -t $CI_REGISTRY/sejuba1/django-saas-backoffice/image:latest .
#     - docker push $CI_REGISTRY/sejuba1/django-saas-backoffice/image:latest

#     # - docker-compose pull $CI_REGISTRY_IMAGE:latest || true
#     # - docker-compose build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
#     # - docker-compose push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#     # - docker-compose push $CI_REGISTRY_IMAGE:latest

# # image: $CI_REGISTRY/sejuba1/django-saas-backoffice/image:latest
# Deploy:
#  stage: deploy
# #  only:
# #     - 'master'

#  script:
#     - ssh $ORGHUB_TEST_USER@$ORGHUB_TEST_SERVER
#     - pwd
#     - rm -f ~/.ssh/id_rsa
    # - 'echo Deploy done: $(date “+%F %H:%M:%S”)'
    
        