image: docker:latest

services:
  - docker:dind

stages:
  - build_image

before_script:
   - docker info
build_image:
  stage: build_image
  script:
    - docker-compose up --build
  
    # - docker login registry.gitlab.com
    # - docker-compose build -t registry.gitlab.com/sejuba1/django-saas-backoffice .
    # - docker-compose push registry.gitlab.com/sejuba1/django-saas-backoffice


    