image: docker:latest

services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
stages:
  - build_image

before_script:
   - docker info
   - 'which ssh-agent || ( apk update && apk add openssh-client)'
   - eval $(ssh-agent -s)
   - apk add curl
   - apk add py-pip
   - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
   - pip install docker-compose
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build_image:
  stage: build_image
  script:
    - docker network create tickethub_net
    # - docker-compose build -t registry.gitlab.com/sejuba1/django-saas-backoffice .
    # - docker-compose push registry.gitlab.com/sejuba1/django-saas-backoffice
    - docker build -t $CI_REGISTRY/group/project/image:latest .
    - docker push $CI_REGISTRY/group/project/image:latest

    # - docker-compose pull $CI_REGISTRY_IMAGE:latest || true
    # - docker-compose build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    # - docker-compose push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # - docker-compose push $CI_REGISTRY_IMAGE:latest
        