image: docker:latest

services:
  - docker:dind

stages:
  - build_image

before_script:
   - docker info
   - 'which ssh-agent || ( apk update && apk add openssh-client)'
   - eval $(ssh-agent -s)
   - apk add curl
   - apk add py-pip
   - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
   - pip install docker-compose

build_image:
  stage: build_image
  script:
    - docker network create tickethub_net
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    
    # - docker-compose build
    # - docker login registry.gitlab.com
    # - docker-compose build -t registry.gitlab.com/sejuba1/django-saas-backoffice .
    # - docker-compose push registry.gitlab.com/sejuba1/django-saas-backoffice


    