stages:
 - build
 - release
 - deploy

build:
 stage: build
 script:
# - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
# - apt-get update && apt-cache policy docker-ce
# - apt-get install -y docker-ce
# - systemctl status docker
 - curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
 - chmod +x /usr/local/bin/docker-compose
 - docker-compose build
 - curl localhost:8000/api/v1/users/

#deploy-containers:
# stage: deploy
# script:
# - export DOCKER_HOST=tcp://192.x.x.x:2375
# - docker-compose down
# - docker-compose up -d
# tags:
# - docker-test
#
#
#prod-deploy-containers:
# stage: deploy
# script:
# - pwd && ls -l
# - ./docker-compose-vps-down.sh
# - ./docker-compose-vps-up.sh
# when: manual
# tags:
# - docker-prod