# Generated by Django 2.1.5 on 2019-02-01 20:29
import os

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


def create_default_public_schema(apps, schema_editor):
    client = apps.get_model('clients', 'Client')
    tenant = client(domain_url=os.getenv('MAIN_DOMAIN_URL', 'localhost'), schema_name='public', name='Main Website',
                    paid_until='2040-10-11', on_trial=False)
    tenant.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('paid_until', models.DateField()),
                ('on_trial', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_default_public_schema, reverse_code=migrations.RunPython.noop)
    ]
