# Generated by Django 2.1.5 on 2019-03-11 13:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('insert_permission', 'Permission to insert to graphql'), ('select_permission', 'Permission to select from graphql'), ('update_permission', 'Permission to update record graphql'), ('delete_permission', 'Permission to delete from graphql')], max_length=30)),
                ('add_args', django.contrib.postgres.fields.jsonb.JSONField(help_text='Args to create permission')),
                ('remove_args', django.contrib.postgres.fields.jsonb.JSONField(help_text='Args to call when deleting permission')),
            ],
        ),
    ]
